/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * @minItems 1
 * @maxItems 200
 */
export type Actions = [
  NavigateAction | ReloadAction | ClickAction | FillAction | SelectAction | SetCheckedAction,
  ...(NavigateAction | ReloadAction | ClickAction | FillAction | SelectAction | SetCheckedAction)[]
];
export type ActionId = string;
export type Path = string;
export type Query = string;
export type RecordRef = ("review" | "completion") | null;
export type TargetAlias = "helpdesk-demo";
export type Kind = "navigate";
export type Sequence = number;
export type ActionId1 = string;
export type Kind1 = "reload";
export type Sequence1 = number;
export type ActionId2 = string;
export type Kind2 = "click";
export type Locator = RoleLocator | LabelLocator;
export type ElementId = string | null;
export type FieldName = string | null;
export type InputType = string | null;
export type ObservedRole = string | null;
export type Tag = string;
export type Name = string;
export type Role = "button" | "link" | "tab" | "menuitem" | "radio" | "checkbox";
export type ElementId1 = string | null;
export type Name1 = string | null;
export type Role1 = "form" | "tabpanel" | "region";
export type Strategy = "role";
export type Label = string;
export type Strategy1 = "label";
export type Sequence2 = number;
export type ActionId3 = string;
export type Kind3 = "fill";
export type Locator1 = RoleLocator | LabelLocator;
export type Sequence3 = number;
export type Value = string;
export type ActionId4 = string;
export type FixtureRef = "actor" | null;
export type Kind4 = "select";
export type Locator2 = RoleLocator | LabelLocator;
export type ObservedValue = string | null;
export type OptionLabel = string;
export type Sequence4 = number;
export type ActionId5 = string;
export type Checked = boolean;
export type Kind5 = "set_checked";
export type Locator3 = RoleLocator | LabelLocator;
export type Sequence5 = number;
export type CapturedAt = string;
export type Completeness = "complete";
export type DocumentCount = number;
export type EventCount = number;
export type ExtensionVersion = string;
export type Category = string;
export type CategoryId = string | null;
export type ContentHash = string;
export type CreatedAt = string;
export type Description = string;
export type Name2 = string;
export type SchemaVersion = 1 | 2 | 3;
export type TargetAlias1 = "helpdesk-demo";
export type ContentHash1 = string;
export type ProfileId = "helpdesk-linked-tickets-v1";
export type Version = 1;
export type WorkflowId = string;
export type WorkflowMode = "verified_preset" | "general";

export interface WorkflowDefinition {
  actions: Actions;
  capture: CaptureProvenance;
  category?: Category;
  category_id?: CategoryId;
  content_hash: ContentHash;
  created_at: CreatedAt;
  description?: Description;
  name: Name2;
  schema_version: SchemaVersion;
  target_alias: TargetAlias1;
  verification_profile: VerificationProfileRef | null;
  workflow_id: WorkflowId;
  workflow_mode?: WorkflowMode;
}
export interface NavigateAction {
  action_id: ActionId;
  destination: PageIdentity;
  kind: Kind;
  sequence: Sequence;
}
export interface PageIdentity {
  path: Path;
  query?: Query;
  record_ref?: RecordRef;
  target_alias: TargetAlias;
}
export interface ReloadAction {
  action_id: ActionId1;
  kind: Kind1;
  page: PageIdentity;
  sequence: Sequence1;
}
export interface ClickAction {
  action_id: ActionId2;
  expected_page_after?: PageIdentity | null;
  kind: Kind2;
  locator: Locator;
  page: PageIdentity;
  sequence: Sequence2;
}
export interface RoleLocator {
  fallback?: ElementFingerprint | null;
  name: Name;
  role: Role;
  scope?: LocatorScope | null;
  strategy: Strategy;
}
export interface ElementFingerprint {
  element_id?: ElementId;
  field_name?: FieldName;
  input_type?: InputType;
  observed_role?: ObservedRole;
  tag: Tag;
}
export interface LocatorScope {
  element_id?: ElementId1;
  name?: Name1;
  role: Role1;
}
export interface LabelLocator {
  fallback?: ElementFingerprint | null;
  label: Label;
  scope?: LocatorScope | null;
  strategy: Strategy1;
}
export interface FillAction {
  action_id: ActionId3;
  kind: Kind3;
  locator: Locator1;
  page: PageIdentity;
  sequence: Sequence3;
  value: Value;
}
export interface SelectAction {
  action_id: ActionId4;
  fixture_ref?: FixtureRef;
  kind: Kind4;
  locator: Locator2;
  observed_value?: ObservedValue;
  option_label: OptionLabel;
  page: PageIdentity;
  sequence: Sequence4;
}
export interface SetCheckedAction {
  action_id: ActionId5;
  checked: Checked;
  kind: Kind5;
  locator: Locator3;
  page: PageIdentity;
  sequence: Sequence5;
}
export interface CaptureProvenance {
  captured_at: CapturedAt;
  completeness: Completeness;
  document_count: DocumentCount;
  event_count: EventCount;
  extension_version: ExtensionVersion;
}
export interface VerificationProfileRef {
  content_hash: ContentHash1;
  profile_id: ProfileId;
  version: Version;
}
